[package]
name = "redis"
version = "0.1.0"
authors = ["hadxu <hadxu123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.20.0"
anyhow = "1.0"
tokio = { version = "1.5.0", features = ["full"] }
